# Generated by Django 3.2.7 on 2021-10-29 13:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_mysql.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default=' ', max_length=20)),
                ('ProfileImg', models.ImageField(default='images/profile_pic/default.png', null=True, upload_to='images/profile_pic/')),
                ('contact', models.CharField(max_length=10)),
                ('Email', models.EmailField(max_length=254)),
                ('address', models.CharField(blank=True, max_length=50)),
                ('website', models.CharField(blank=True, default='', max_length=30, null=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('N', 'Prefer Not To Say')], default='N', max_length=1)),
                ('acc_type', models.CharField(choices=[('pvt', 'Private'), ('pub', 'Public')], default='pub', max_length=3)),
                ('activity_status', models.BooleanField(default=False)),
                ('story_share', models.BooleanField(default=False)),
                ('close_friends', django_mysql.models.ListCharField(models.CharField(max_length=10), blank=True, default=[], max_length=66, null=True, size=6)),
                ('hide_story', django_mysql.models.ListCharField(models.CharField(max_length=10), blank=True, default=[], max_length=66, null=True, size=6)),
                ('blocked_users', django_mysql.models.ListCharField(models.CharField(max_length=10), blank=True, default=[], max_length=66, null=True, size=6)),
                ('restricted_users', django_mysql.models.ListCharField(models.CharField(max_length=10), blank=True, default=[], max_length=66, null=True, size=6)),
                ('followers', django_mysql.models.ListCharField(models.CharField(max_length=10), blank=True, default=[], max_length=66, null=True, size=6)),
                ('following', django_mysql.models.ListCharField(models.CharField(max_length=10), blank=True, default=[], max_length=66, null=True, size=6)),
                ('saved', django_mysql.models.ListCharField(models.CharField(max_length=10), blank=True, default=[], max_length=66, null=True, size=6)),
                ('follow_request', django_mysql.models.ListCharField(models.CharField(max_length=10), blank=True, default=[], max_length=66, null=True, size=6)),
                ('bio', models.CharField(blank=True, default=' ', max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
