# Generated by Django 3.2.7 on 2021-10-31 13:30

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('front', '0002_auto_20211031_1141'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploadTime', models.DateTimeField(default=datetime.datetime(2021, 10, 31, 19, 0, 22, 401954))),
                ('likes', django_mysql.models.ListCharField(models.CharField(max_length=10), blank=True, default=[], max_length=66, null=True, size=6)),
                ('caption', models.CharField(max_length=300)),
                ('shares', models.IntegerField(default=0)),
                ('saved', models.IntegerField(default=0)),
                ('comments', django_mysql.models.ListCharField(models.CharField(max_length=10), blank=True, default=[], max_length=66, null=True, size=6)),
                ('Showimage', models.ImageField(default=' ', upload_to='images/posts/')),
                ('archived', models.BooleanField(default=False)),
                ('mentions', django_mysql.models.ListCharField(models.CharField(max_length=50), blank=True, max_length=306, null=True, size=6)),
                ('Location', models.CharField(blank=True, max_length=50, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PostImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/posts/')),
                ('Post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='front.post')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=50, null=True)),
                ('reply_to', models.CharField(blank=True, max_length=100, null=True)),
                ('uploadTime', models.DateTimeField(default=datetime.datetime(2021, 10, 31, 19, 0, 22, 401954))),
                ('likes', django_mysql.models.ListCharField(models.CharField(max_length=10), blank=True, max_length=66, null=True, size=6)),
                ('replies', django_mysql.models.ListCharField(models.CharField(max_length=10), blank=True, max_length=66, null=True, size=6)),
                ('Post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='front.post')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
