# Generated by Django 3.2.7 on 2021-11-05 10:55

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0004_auto_20211105_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='Profile',
            field=models.ForeignKey(default='sandeshj_07', on_delete=django.db.models.deletion.CASCADE, to='front.profile'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='uploadTime',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 5, 16, 25, 8, 96716)),
        ),
        migrations.AlterField(
            model_name='post',
            name='profile',
            field=models.ForeignKey(default='sandeshj_07', on_delete=django.db.models.deletion.CASCADE, to='front.profile'),
        ),
        migrations.AlterField(
            model_name='post',
            name='uploadTime',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 5, 16, 25, 8, 96716)),
        ),
    ]
