# Generated by Django 3.2.7 on 2021-11-05 11:00

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0006_auto_20211105_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='front.profile'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comment',
            name='uploadTime',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 5, 16, 29, 57, 292543)),
        ),
        migrations.AlterField(
            model_name='post',
            name='uploadTime',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 5, 16, 29, 57, 292543)),
        ),
    ]
