# Generated by Django 3.2.7 on 2021-11-07 07:41

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('front', '0009_auto_20211106_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='uploadTime',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 7, 13, 11, 24, 174297)),
        ),
        migrations.AlterField(
            model_name='post',
            name='uploadTime',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 7, 13, 11, 24, 167345)),
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploadTime', models.DateTimeField(default=datetime.datetime(2021, 11, 7, 13, 11, 24, 175294))),
                ('type', models.CharField(choices=[('p', 'public'), ('c', 'close_friends')], default='p', max_length=20)),
                ('Image', models.ImageField(upload_to='images/stories/')),
                ('views', django_mysql.models.ListCharField(models.CharField(max_length=10), blank=True, default=[], max_length=66, null=True, size=6)),
                ('shares', models.IntegerField(default=0)),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
