# Generated by Django 3.2.7 on 2021-11-08 07:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0010_auto_20211107_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='uploadTime',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 8, 13, 3, 54, 561438)),
        ),
        migrations.AlterField(
            model_name='post',
            name='uploadTime',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 8, 13, 3, 54, 561438)),
        ),
        migrations.AlterField(
            model_name='story',
            name='uploadTime',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 8, 13, 3, 54, 561438)),
        ),
    ]
