# Generated by Django 3.2.7 on 2021-11-11 04:09

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('front', '0011_auto_20211108_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='uploadTime',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 11, 9, 39, 10, 403972)),
        ),
        migrations.AlterField(
            model_name='post',
            name='uploadTime',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 11, 9, 39, 10, 396802)),
        ),
        migrations.AlterField(
            model_name='profile',
            name='ProfileImg',
            field=models.ImageField(default='media/images/profile_pic/default.png', null=True, upload_to='images/profile_pic/'),
        ),
        migrations.AlterField(
            model_name='story',
            name='uploadTime',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 11, 9, 39, 10, 403972)),
        ),
        migrations.CreateModel(
            name='ChatRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=' Chatroom', max_length=25)),
                ('Users', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ChatMsg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('seen', 'seen'), ('delivered', 'delivered'), ('sending', 'sending')], default='sending', max_length=10)),
                ('sendTime', models.DateTimeField(default=datetime.datetime(2021, 11, 11, 9, 39, 10, 403972))),
                ('content', models.TextField(max_length=6000)),
                ('Chatroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='front.chatroom')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
